# GitHub Action for generating a contribution graph with a snake eating your contributions.
# GitHub Action для создания графика вкладов со змеей, пожирающей ваши взносы.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
# Управляет запуском действия. Это действие выполняется каждые 6 часов.
on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"
# This command allows us to run the Action automatically from the Actions tab.

  workflow_dispatch:

  # run on every push on the master branch
  push: {branches: ["master", "main"]}

# The sequence of runs in this workflow:
# Последовательность прогонов в этом рабочем процессе:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
            assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          # a github token is required to fetch the contribution calendar from github API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
